// L.10 / Fase 1.D — Public share-link viewer. No auth required. Resolves the
// token via service role, increments the view counter, and renders the
// matching dashboard read-only with an optional watermark email banner.

import { notFound } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/database.types";
import { CompanyDashboardView } from "@/components/dashboards/company-dashboard-view";
import { FundDashboardView } from "@/components/dashboards/fund-dashboard-view";

export const dynamic = "force-dynamic";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;

function admin() {
  return createClient<Database>(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export default async function PublicSharePage({ params }: { params: { token: string } }) {
  const supabase = admin();

  const { data: link } = await supabase
    .from("share_links")
    .select("id, kind, target_company_id, watermark_email, view_count, expires_at, organization_id")
    .eq("token", params.token)
    .maybeSingle();

  if (!link) return notFound();
  if (link.expires_at && new Date(link.expires_at).getTime() < Date.now()) {
    return <ExpiredPage />;
  }
  if (link.kind !== "fund_dashboard" && link.kind !== "company_dashboard") {
    // Legacy lp_letter shares belong to /share/[token].
    return notFound();
  }

  // Bump view count. Best-effort; ignore errors so the page still renders.
  await supabase
    .from("share_links")
    .update({ view_count: (link.view_count ?? 0) + 1 } as any)
    .eq("id", link.id);

  // Resolve org name + (when company) the company shell. Service role
  // bypasses RLS — that's fine because we already verified the token.
  const { data: org } = await supabase
    .from("organizations")
    .select("name, logo_url")
    .eq("id", link.organization_id)
    .maybeSingle();

  let companyName: string | null = null;
  if (link.kind === "company_dashboard" && link.target_company_id) {
    const { data: c } = await supabase
      .from("companies")
      .select("name")
      .eq("id", link.target_company_id)
      .maybeSingle();
    companyName = c?.name ?? null;
  }

  const title = link.kind === "fund_dashboard"
    ? `${org?.name ?? "Fund"} — overview`
    : `${companyName ?? "Company"} — dashboard`;

  return (
    <div className="min-h-screen bg-paper">
      <header className="bg-white border-b border-line px-8 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            {org?.logo_url ? (
              /* eslint-disable-next-line @next/next/no-img-element */
              <img src={org.logo_url} alt={org.name ?? ""} className="h-8 w-8 rounded-md object-contain bg-white border border-line" />
            ) : null}
            <div>
              <h1 className="text-base font-serif font-semibold text-ink">{title}</h1>
              {org?.name && <p className="text-[11px] text-muted">{org.name}</p>}
            </div>
          </div>
          <div className="text-[10px] text-muted uppercase tracking-[0.16em]">Read-only · Pulso</div>
        </div>
      </header>

      {link.watermark_email && (
        <div className="bg-gold/10 border-b border-gold/30 px-8 py-2 text-[11px] text-navy text-center">
          Shared with {link.watermark_email}
        </div>
      )}

      <main className="max-w-5xl mx-auto px-8 py-6">
        {link.kind === "fund_dashboard" ? (
          <FundDashboardView />
        ) : link.target_company_id ? (
          <CompanyDashboardView companyId={link.target_company_id} />
        ) : (
          <p className="text-sm text-muted">Dashboard target missing.</p>
        )}
      </main>

      <footer className="max-w-5xl mx-auto px-8 py-6 text-[10px] text-muted text-center">
        Generated by Pulso
      </footer>
    </div>
  );
}

function ExpiredPage() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-paper">
      <div className="bg-white rounded-xl border border-line p-8 max-w-md text-center">
        <h1 className="text-lg font-serif font-semibold text-ink">Link expired</h1>
        <p className="text-sm text-muted mt-2">Ask the fund team for a fresh link.</p>
      </div>
    </div>
  );
}
