// Auto-generated by Supabase. Regenerate with:
//   supabase gen types typescript --project-id wmsmptedodmtmtrdnaud > lib/database.types.ts
// (or via the Supabase MCP `generate_typescript_types`)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      companies: {
        Row: {
          country: string | null
          created_at: string
          description: string | null
          flag: string | null
          founder_email: string | null
          founder_name: string | null
          founder_role: string | null
          id: string
          invested_usd: number
          last_update_at: string | null
          name: string
          organization_id: string
          ownership_pct: number
          sector: string | null
          slug: string
          stage: Database["public"]["Enums"]["company_stage"]
          status: Database["public"]["Enums"]["company_status"]
        }
        Insert: {
          country?: string | null
          created_at?: string
          description?: string | null
          flag?: string | null
          founder_email?: string | null
          founder_name?: string | null
          founder_role?: string | null
          id?: string
          invested_usd?: number
          last_update_at?: string | null
          name: string
          organization_id: string
          ownership_pct?: number
          sector?: string | null
          slug: string
          stage: Database["public"]["Enums"]["company_stage"]
          status?: Database["public"]["Enums"]["company_status"]
        }
        Update: {
          country?: string | null
          created_at?: string
          description?: string | null
          flag?: string | null
          founder_email?: string | null
          founder_name?: string | null
          founder_role?: string | null
          id?: string
          invested_usd?: number
          last_update_at?: string | null
          name?: string
          organization_id?: string
          ownership_pct?: number
          sector?: string | null
          slug?: string
          stage?: Database["public"]["Enums"]["company_stage"]
          status?: Database["public"]["Enums"]["company_status"]
        }
        Relationships: []
      }
      form_recipients: {
        Row: { company_id: string; created_at: string; form_id: string }
        Insert: { company_id: string; created_at?: string; form_id: string }
        Update: { company_id?: string; created_at?: string; form_id?: string }
        Relationships: []
      }
      form_submissions: {
        Row: {
          ai_extracted: boolean
          ai_flags_json: Json | null
          company_id: string
          data_json: Json
          form_id: string
          id: string
          submitted_at: string
          submitted_by_email: string | null
        }
        Insert: {
          ai_extracted?: boolean
          ai_flags_json?: Json | null
          company_id: string
          data_json?: Json
          form_id: string
          id?: string
          submitted_at?: string
          submitted_by_email?: string | null
        }
        Update: {
          ai_extracted?: boolean
          ai_flags_json?: Json | null
          company_id?: string
          data_json?: Json
          form_id?: string
          id?: string
          submitted_at?: string
          submitted_by_email?: string | null
        }
        Relationships: []
      }
      forms: {
        Row: {
          active: boolean
          cadence: Database["public"]["Enums"]["form_cadence"]
          created_at: string
          fields_json: Json
          id: string
          last_sent_at: string | null
          name: string
          organization_id: string
          response_rate: number
          sent_to_count: number
          slug: string
        }
        Insert: {
          active?: boolean
          cadence: Database["public"]["Enums"]["form_cadence"]
          created_at?: string
          fields_json?: Json
          id?: string
          last_sent_at?: string | null
          name: string
          organization_id: string
          response_rate?: number
          sent_to_count?: number
          slug: string
        }
        Update: {
          active?: boolean
          cadence?: Database["public"]["Enums"]["form_cadence"]
          created_at?: string
          fields_json?: Json
          id?: string
          last_sent_at?: string | null
          name?: string
          organization_id?: string
          response_rate?: number
          sent_to_count?: number
          slug?: string
        }
        Relationships: []
      }
      lps: {
        Row: {
          commitment_usd: number
          country: string | null
          created_at: string
          email: string | null
          id: string
          last_access_at: string | null
          name: string
          organization_id: string
          type: Database["public"]["Enums"]["lp_type"]
        }
        Insert: {
          commitment_usd: number
          country?: string | null
          created_at?: string
          email?: string | null
          id?: string
          last_access_at?: string | null
          name: string
          organization_id: string
          type: Database["public"]["Enums"]["lp_type"]
        }
        Update: {
          commitment_usd?: number
          country?: string | null
          created_at?: string
          email?: string | null
          id?: string
          last_access_at?: string | null
          name?: string
          organization_id?: string
          type?: Database["public"]["Enums"]["lp_type"]
        }
        Relationships: []
      }
      metrics: {
        Row: {
          arr_usd: number | null
          burn_usd: number | null
          cash_usd: number | null
          company_id: string
          created_at: string
          headcount: number | null
          id: string
          quarter: string
          revenue_usd: number | null
        }
        Insert: {
          arr_usd?: number | null
          burn_usd?: number | null
          cash_usd?: number | null
          company_id: string
          created_at?: string
          headcount?: number | null
          id?: string
          quarter: string
          revenue_usd?: number | null
        }
        Update: {
          arr_usd?: number | null
          burn_usd?: number | null
          cash_usd?: number | null
          company_id?: string
          created_at?: string
          headcount?: number | null
          id?: string
          quarter?: string
          revenue_usd?: number | null
        }
        Relationships: []
      }
      organizations: {
        Row: {
          created_at: string
          currency: string
          deployed_usd: number | null
          id: string
          name: string
          size_usd: number | null
          slug: string
          updated_at: string
          vintage: number | null
        }
        Insert: {
          created_at?: string
          currency?: string
          deployed_usd?: number | null
          id?: string
          name: string
          size_usd?: number | null
          slug: string
          updated_at?: string
          vintage?: number | null
        }
        Update: {
          created_at?: string
          currency?: string
          deployed_usd?: number | null
          id?: string
          name?: string
          size_usd?: number | null
          slug?: string
          updated_at?: string
          vintage?: number | null
        }
        Relationships: []
      }
      share_links: {
        Row: {
          created_at: string
          expires_at: string | null
          id: string
          lp_id: string | null
          organization_id: string
          token: string
          view_count: number
          watermark_email: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string | null
          id?: string
          lp_id?: string | null
          organization_id: string
          token: string
          view_count?: number
          watermark_email?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string | null
          id?: string
          lp_id?: string | null
          organization_id?: string
          token?: string
          view_count?: number
          watermark_email?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          kind: string
          link: string | null
          metadata_json: Json | null
          organization_id: string
          read_at: string | null
          title: string
          user_id: string | null
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          kind: string
          link?: string | null
          metadata_json?: Json | null
          organization_id: string
          read_at?: string | null
          title: string
          user_id?: string | null
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: string
          link?: string | null
          metadata_json?: Json | null
          organization_id?: string
          read_at?: string | null
          title?: string
          user_id?: string | null
        }
        Relationships: []
      }
      user_invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          organization_id: string
          revoked_at: string | null
          role: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          organization_id: string
          revoked_at?: string | null
          role?: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          organization_id?: string
          revoked_at?: string | null
          role?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          auth_user_id: string | null
          created_at: string
          email: string
          id: string
          name: string | null
          organization_id: string | null
          role: string
        }
        Insert: {
          auth_user_id?: string | null
          created_at?: string
          email: string
          id?: string
          name?: string | null
          organization_id?: string | null
          role?: string
        }
        Update: {
          auth_user_id?: string | null
          created_at?: string
          email?: string
          id?: string
          name?: string | null
          organization_id?: string | null
          role?: string
        }
        Relationships: []
      }
    }
    Views: {
      form_recipient_summary: {
        Row: {
          company_ids: string[] | null
          form_id: string | null
          organization_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      get_lp_letters: { Args: never; Returns: Json }
      get_org_members: { Args: never; Returns: Json }
      run_metric_alerts: { Args: never; Returns: Json }
      get_public_form: {
        Args: { p_company_slug: string; p_form_slug: string }
        Returns: Json
      }
      get_share_letter: { Args: { p_token: string }; Returns: Json }
      submit_public_form: {
        Args: {
          p_ai_extracted?: boolean
          p_company_slug: string
          p_data: Json
          p_form_slug: string
        }
        Returns: string
      }
      user_org_id: { Args: never; Returns: string }
    }
    Enums: {
      company_stage: "Pre-seed" | "Seed" | "Series A" | "Series B"
      company_status: "healthy" | "watch" | "critical" | "no_data"
      form_cadence: "monthly" | "quarterly" | "annual" | "ad_hoc"
      form_field_type:
        | "currency"
        | "number"
        | "percent"
        | "text"
        | "longtext"
        | "select"
        | "date"
      lp_type: "Family Office" | "Institutional" | "Fund of Funds" | "Individual"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
