// Auto-generated by Supabase. Regenerate with:
//   supabase gen types typescript --project-id wmsmptedodmtmtrdnaud > lib/database.types.ts
// (or via the Supabase MCP `generate_typescript_types`)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      companies: {
        Row: {
          country: string | null
          created_at: string
          description: string | null
          flag: string | null
          founder_email: string | null
          founder_name: string | null
          founder_role: string | null
          id: string
          invested_usd: number
          last_update_at: string | null
          name: string
          organization_id: string
          ownership_pct: number
          sector: string | null
          slug: string
          stage: Database["public"]["Enums"]["company_stage"]
          status: Database["public"]["Enums"]["company_status"]
        }
        Insert: {
          country?: string | null
          created_at?: string
          description?: string | null
          flag?: string | null
          founder_email?: string | null
          founder_name?: string | null
          founder_role?: string | null
          id?: string
          invested_usd?: number
          last_update_at?: string | null
          name: string
          organization_id: string
          ownership_pct?: number
          sector?: string | null
          slug: string
          stage: Database["public"]["Enums"]["company_stage"]
          status?: Database["public"]["Enums"]["company_status"]
        }
        Update: {
          country?: string | null
          created_at?: string
          description?: string | null
          flag?: string | null
          founder_email?: string | null
          founder_name?: string | null
          founder_role?: string | null
          id?: string
          invested_usd?: number
          last_update_at?: string | null
          name?: string
          organization_id?: string
          ownership_pct?: number
          sector?: string | null
          slug?: string
          stage?: Database["public"]["Enums"]["company_stage"]
          status?: Database["public"]["Enums"]["company_status"]
        }
        Relationships: [
          {
            foreignKeyName: "companies_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      form_submissions: {
        Row: {
          ai_extracted: boolean
          ai_flags_json: Json | null
          company_id: string
          data_json: Json
          form_id: string
          id: string
          submitted_at: string
          submitted_by_email: string | null
        }
        Insert: {
          ai_extracted?: boolean
          ai_flags_json?: Json | null
          company_id: string
          data_json?: Json
          form_id: string
          id?: string
          submitted_at?: string
          submitted_by_email?: string | null
        }
        Update: {
          ai_extracted?: boolean
          ai_flags_json?: Json | null
          company_id?: string
          data_json?: Json
          form_id?: string
          id?: string
          submitted_at?: string
          submitted_by_email?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "form_submissions_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "form_submissions_form_id_fkey"
            columns: ["form_id"]
            isOneToOne: false
            referencedRelation: "forms"
            referencedColumns: ["id"]
          },
        ]
      }
      forms: {
        Row: {
          active: boolean
          cadence: Database["public"]["Enums"]["form_cadence"]
          created_at: string
          fields_json: Json
          id: string
          last_sent_at: string | null
          name: string
          organization_id: string
          response_rate: number
          sent_to_count: number
          slug: string
        }
        Insert: {
          active?: boolean
          cadence: Database["public"]["Enums"]["form_cadence"]
          created_at?: string
          fields_json?: Json
          id?: string
          last_sent_at?: string | null
          name: string
          organization_id: string
          response_rate?: number
          sent_to_count?: number
          slug: string
        }
        Update: {
          active?: boolean
          cadence?: Database["public"]["Enums"]["form_cadence"]
          created_at?: string
          fields_json?: Json
          id?: string
          last_sent_at?: string | null
          name?: string
          organization_id?: string
          response_rate?: number
          sent_to_count?: number
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "forms_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      lps: {
        Row: {
          commitment_usd: number
          country: string | null
          created_at: string
          email: string | null
          id: string
          last_access_at: string | null
          name: string
          organization_id: string
          type: Database["public"]["Enums"]["lp_type"]
        }
        Insert: {
          commitment_usd: number
          country?: string | null
          created_at?: string
          email?: string | null
          id?: string
          last_access_at?: string | null
          name: string
          organization_id: string
          type: Database["public"]["Enums"]["lp_type"]
        }
        Update: {
          commitment_usd?: number
          country?: string | null
          created_at?: string
          email?: string | null
          id?: string
          last_access_at?: string | null
          name?: string
          organization_id?: string
          type?: Database["public"]["Enums"]["lp_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lps_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      metrics: {
        Row: {
          arr_usd: number | null
          burn_usd: number | null
          cash_usd: number | null
          company_id: string
          created_at: string
          headcount: number | null
          id: string
          quarter: string
          revenue_usd: number | null
        }
        Insert: {
          arr_usd?: number | null
          burn_usd?: number | null
          cash_usd?: number | null
          company_id: string
          created_at?: string
          headcount?: number | null
          id?: string
          quarter: string
          revenue_usd?: number | null
        }
        Update: {
          arr_usd?: number | null
          burn_usd?: number | null
          cash_usd?: number | null
          company_id?: string
          created_at?: string
          headcount?: number | null
          id?: string
          quarter?: string
          revenue_usd?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "metrics_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          clerk_org_id: string | null
          created_at: string
          currency: string
          deployed_usd: number | null
          id: string
          name: string
          size_usd: number | null
          slug: string
          updated_at: string
          vintage: number | null
        }
        Insert: {
          clerk_org_id?: string | null
          created_at?: string
          currency?: string
          deployed_usd?: number | null
          id?: string
          name: string
          size_usd?: number | null
          slug: string
          updated_at?: string
          vintage?: number | null
        }
        Update: {
          clerk_org_id?: string | null
          created_at?: string
          currency?: string
          deployed_usd?: number | null
          id?: string
          name?: string
          size_usd?: number | null
          slug?: string
          updated_at?: string
          vintage?: number | null
        }
        Relationships: []
      }
      share_links: {
        Row: {
          created_at: string
          expires_at: string | null
          id: string
          lp_id: string | null
          organization_id: string
          token: string
          view_count: number
          watermark_email: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string | null
          id?: string
          lp_id?: string | null
          organization_id: string
          token: string
          view_count?: number
          watermark_email?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string | null
          id?: string
          lp_id?: string | null
          organization_id?: string
          token?: string
          view_count?: number
          watermark_email?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "share_links_lp_id_fkey"
            columns: ["lp_id"]
            isOneToOne: false
            referencedRelation: "lps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "share_links_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          clerk_user_id: string | null
          created_at: string
          email: string
          id: string
          name: string | null
          organization_id: string
          role: string
        }
        Insert: {
          clerk_user_id?: string | null
          created_at?: string
          email: string
          id?: string
          name?: string | null
          organization_id: string
          role?: string
        }
        Update: {
          clerk_user_id?: string | null
          created_at?: string
          email?: string
          id?: string
          name?: string | null
          organization_id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: {
      company_stage: "Pre-seed" | "Seed" | "Series A" | "Series B"
      company_status: "healthy" | "watch" | "critical" | "no_data"
      form_cadence: "monthly" | "quarterly" | "annual" | "ad_hoc"
      form_field_type:
        | "currency"
        | "number"
        | "percent"
        | "text"
        | "longtext"
        | "select"
        | "date"
      lp_type:
        | "Family Office"
        | "Institutional"
        | "Fund of Funds"
        | "Individual"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
